# DW Playbook Builder
# Usage: just <input.tex> <output.pdf>

IMAGE_NAME := "ghcr.io/ryankeepers/dw-playbooks-tex:latest"

default:
    just -l

# Generate a DW playbook PDF from a tex file.
# Usage: just gen <version> <mode> <input.tex> <output.pdf>
# - version: 1 or 2 (for DW 1 or DW 2)
# - mode: l or d (for light or dark mode)
# - input.tex: source tex file
# - output.pdf: output PDF file
[group('PDF Generation')]
gen version mode texfile output_pdf:
    ./gen-pdf.sh {{version}} {{mode}} {{texfile}} {{output_pdf}}

# Build the Docker image locally
[group('docker')]
build-image:
    @echo "Building Docker image..."
    docker build -t {{IMAGE_NAME}} .
    @echo "✅ Image built successfully"

# Clean auxiliary files generated by LaTeX
[group('cleanup')]
clean texfile:
    rm -f "*.aux" "*.log" "*.out" "*.fls" "*.fdb_latexmk" "*.toc" "*.nav" "*.snm"

# Clean up any spilled .cls/.sty files from development (run after building image)
[group('cleanup')]
clean-spillover:
    @echo "Cleaning up any spilled .cls/.sty files..."
    @rm -f dw1_playbook.cls dw1_playbook.sty dw2_playbook.cls dw2_playbook.sty
    @if [ -d texmf ]; then \
        echo "Removing texmf directory..."; \
        rm -rf texmf; \
    fi
    @echo "✅ Spillover cleanup complete"
